version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.8.4

    container_name: qdrant_rag_tob
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data_rag_tob:/qdrant/storage
    restart: always

volumes:
  qdrant_data_rag_tob:
